### ISSUE TITLE
error when `script` has attrs

### ISSUE THREAD

**Issue by KABBOUCHI** [sajansharmanz/prettier-plugin-edgejs#7] opened 2024-09-02 17:56 UTC
```edge
<script type="module">

</script>
```

```log
Error: {"message":"Unexpected token: operator «<»","filename":"file1.js","line":1,"col":0,"pos":0}
```

**Comment by sajansharmanz** [comment] 2024-09-02 21:09
Hey,

Thanks for the bug.

I've found what the issue is, i'll try get this sorted during my day tomorrow.

Will keep you updated.

Cheers,

**Comment by sajansharmanz** [comment] 2024-09-03 08:40
@KABBOUCHI this should be fixed in the latest release of the plugin.

Please note due to an issue with using edge tags inside of <script> and <style> tags - i've had to disable the formatters I was using inside the plugin. So the plugin will indent your code to the minimum level it should be but it won't format the content for now.

Please see more about this at https://github.com/sajansharmanz/prettier-plugin-edgejs/issues/7

I will look for a way to allow CSS and JS formatting but will need to investigate and figure it out first.

**Closed** 2024-09-03 08:41 UTC
Labels: bug
